# docker network create utilities
networks:
  utilities:
    external: true

services:
  tune-tide:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/opt/node-user/.ssh
      - ../.devcontainer/zshrc:/opt/node-user/.zshrc
      - ..:/opt/node-user/code
    command: ["tail -f /dev/null"]
    networks:
      - utilities

  tune-tide-postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../.devcontainer/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - utilities

  tune-tide-weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.8
    # ports:
    # - 8080:8080
    # - 50051:50051
    # restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
    networks:
      - utilities

  tune-tide-minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - utilities
